<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>

    <OutputType>Library</OutputType>
    <AssemblyName>JupiterX</AssemblyName>
    <RootNamespace>JupiterX</RootNamespace>

    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU</Platforms>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Prefer32Bit>false</Prefer32Bit>

    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>

    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>

    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>


  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>

    <DefineConstants>DEBUG;TRACE</DefineConstants>

    <OutputPath>bin\Debug\</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>

    <DefineConstants>TRACE</DefineConstants>

    <OutputPath>bin\Release\</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*" />
  </ItemGroup>
	
  <ItemGroup>

    <Reference Include="0Harmony">
      <HintPath>..\..\MelonRefs\Melon\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="MelonLoader">
      <HintPath>..\..\MelonRefs\Melon\MelonLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Preload">
      <HintPath>..\..\MelonRefs\Melon\Preload.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2Cpp">
      <HintPath>..\..\MelonRefs\Melon\Il2Cpp.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2CppInterop.Common">
      <HintPath>..\..\MelonRefs\Melon\Il2CppInterop.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2CppInterop.Generator">
      <HintPath>..\..\MelonRefs\Melon\Il2CppInterop.Generator.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2CppInterop.HarmonySupport">
      <HintPath>..\..\MelonRefs\Melon\Il2CppInterop.HarmonySupport.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>..\..\MelonRefs\Melon\Il2CppInterop.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="JNISharp">
      <HintPath>..\..\MelonRefs\Melon\JNISharp.dll</HintPath>
      <Private>false</Private>
    </Reference>

  </ItemGroup>
	
  <ItemGroup>

    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\MelonRefs\AssemblyCSharpStuff\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>..\..\MelonRefs\AssemblyCSharpStuff\Assembly-CSharp-firstpass.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2CppMono.Security">
      <HintPath>..\..\MelonRefs\AssemblyCSharpStuff\Il2CppMono.Security.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2Cppmscorlib">
      <HintPath>..\..\MelonRefs\AssemblyCSharpStuff\Il2Cppmscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2CppPhoton3Unity3D">
      <HintPath>..\..\MelonRefs\AssemblyCSharpStuff\Il2CppPhoton3Unity3D.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2CppPhotonChat">
      <HintPath>..\..\MelonRefs\AssemblyCSharpStuff\Il2CppPhotonChat.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2CppPhotonRealtime">
      <HintPath>..\..\MelonRefs\AssemblyCSharpStuff\Il2CppPhotonRealtime.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2CppPhotonUnityNetworking">
      <HintPath>..\..\MelonRefs\AssemblyCSharpStuff\Il2CppPhotonUnityNetworking.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2CppPhotonUnityNetworking.Utilities">
      <HintPath>..\..\MelonRefs\AssemblyCSharpStuff\Il2CppPhotonUnityNetworking.Utilities.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2CppPhotonVoice">
      <HintPath>..\..\MelonRefs\AssemblyCSharpStuff\Il2CppPhotonVoice.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2CppPhotonVoice.API">
      <HintPath>..\..\MelonRefs\AssemblyCSharpStuff\Il2CppPhotonVoice.API.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2CppPhotonVoice.PUN">
      <HintPath>..\..\MelonRefs\AssemblyCSharpStuff\Il2CppPhotonVoice.PUN.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2CppPlayFab">
      <HintPath>..\..\MelonRefs\AssemblyCSharpStuff\Il2CppPlayFab.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Il2Cpp__Generated">
      <HintPath>..\..\MelonRefs\AssemblyCSharpStuff\Il2Cpp__Generated.dll</HintPath>
      <Private>false</Private>
    </Reference>

  </ItemGroup>


  <ItemGroup>

    <Reference Include="UnityEngine">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.AccessibilityModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.AccessibilityModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.AIModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.AIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.AndroidJNIModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.AndroidJNIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.AnimationModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.ARModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.ARModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.AudioModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.ClothModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.ClothModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.ClusterInputModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.ClusterInputModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.ClusterRendererModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.ClusterRendererModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.CrashReportingModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.CrashReportingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.DirectorModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.DirectorModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.DSPGraphModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.DSPGraphModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.GameCenterModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.GameCenterModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.GIModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.GIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.GridModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.GridModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.HotReloadModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.HotReloadModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.InputModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.InputModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.JSONSerializeModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.LocalizationModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.LocalizationModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.NVIDIAModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.NVIDIAModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.ParticleSystemModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.PerformanceReportingModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.PerformanceReportingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.Physics2DModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.ProfilerModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.ProfilerModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.ScreenCaptureModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.ScreenCaptureModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.SharedInternalsModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.SharedInternalsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.SpatialTracking">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.SpatialTracking.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.SpriteMaskModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.SpriteMaskModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.SpriteShapeModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.SpriteShapeModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.StreamingModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.StreamingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.SubstanceModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.SubstanceModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.SubsystemsModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.SubsystemsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.TerrainModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.TerrainPhysicsModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.TerrainPhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.TextCoreFontEngineModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.TextCoreTextEngineModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.TilemapModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.TilemapModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.TLSModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.TLSModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UI">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.UIElementsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UIElementsNativeModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.UIElementsNativeModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UIModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UmbraModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.UmbraModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UNETModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.UNETModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UnityAnalyticsModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.UnityAnalyticsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UnityConnectModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.UnityConnectModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UnityCurlModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.UnityCurlModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UnityTestProtocolModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.UnityTestProtocolModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UnityWebRequestAudioModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.UnityWebRequestModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UnityWebRequestTextureModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.UnityWebRequestWWWModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.VehiclesModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.VehiclesModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.VFXModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.VFXModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.VideoModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.VideoModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.VirtualTexturingModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.VirtualTexturingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.VRModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.VRModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.WindModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.WindModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.XRModule">
      <HintPath>..\..\MelonRefs\Unity\UnityEngine.XRModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

  </ItemGroup>


  <ItemGroup>

    <Reference Include="Unity.Animation.Rigging">
      <HintPath>..\..\MelonRefs\Unity\Unity.Animation.Rigging.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.Burst">
      <HintPath>..\..\MelonRefs\Unity\Unity.Burst.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.InputSystem">
      <HintPath>..\..\MelonRefs\Unity\Unity.InputSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.Mathematics">
      <HintPath>..\..\MelonRefs\Unity\Unity.Mathematics.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>..\..\MelonRefs\Unity\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.RenderPipelines.Universal.Runtime">
      <HintPath>..\..\MelonRefs\Unity\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\MelonRefs\Unity\Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.XR.CoreUtils">
      <HintPath>..\..\MelonRefs\Unity\Unity.XR.CoreUtils.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.XR.Interaction.Toolkit">
      <HintPath>..\..\MelonRefs\Unity\Unity.XR.Interaction.Toolkit.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.XR.Interaction.Toolkit.Samples.StarterAssets">
      <HintPath>..\..\MelonRefs\Unity\Unity.XR.Interaction.Toolkit.Samples.StarterAssets.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.XR.Management">
      <HintPath>..\..\MelonRefs\Unity\Unity.XR.Management.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.XR.Oculus">
      <HintPath>..\..\MelonRefs\Unity\Unity.XR.Oculus.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.XR.OpenXR">
      <HintPath>..\..\MelonRefs\Unity\Unity.XR.OpenXR.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.XR.OpenXR.Features.ConformanceAutomation">
      <HintPath>..\..\MelonRefs\Unity\Unity.XR.OpenXR.Features.ConformanceAutomation.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.XR.OpenXR.Features.MetaQuestSupport">
      <HintPath>..\..\MelonRefs\Unity\Unity.XR.OpenXR.Features.MetaQuestSupport.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.XR.OpenXR.Features.MockRuntime">
      <HintPath>..\..\MelonRefs\Unity\Unity.XR.OpenXR.Features.MockRuntime.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.XR.OpenXR.Features.OculusQuestSupport">
      <HintPath>..\..\MelonRefs\Unity\Unity.XR.OpenXR.Features.OculusQuestSupport.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.XR.OpenXR.Features.RuntimeDebugger">
      <HintPath>..\..\MelonRefs\Unity\Unity.XR.OpenXR.Features.RuntimeDebugger.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="Valve.Newtonsoft.Json">
      <HintPath>..\..\MelonRefs\Melon\Valve.Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>